version: '3'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    networks:
      air_db:
  restapi:
    image: manoskoutoulakis/obc_client:latest
    build:
      # Uncomment only for production purposes TODO (make another one compose)
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - airflowserver
    restart: always
    volumes:
      # docker connect with client to get info or execute commands
      - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment only for production purposes TODO (make another one compose)
      - ./client:/code
      - datavolume:/code/generated_dags
    ports:
      - "5000:5000"
    networks:
      air_rest:
        ipv4_address: 172.18.0.4
      air_db:      
    container_name: OBC_client      

  airflowserver:
    image: puckel/docker-airflow:1.10.1
    build:
      context: https://github.com/puckel/docker-airflow.git#1.10.1
      dockerfile: Dockerfile
      args:
        AIRFLOW_DEPS: gcp_api,s3
        PYTHON_DEPS: sqlalchemy==1.2.0
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
    volumes:
      - datavolume:/usr/local/airflow/dags
      # Folder where airflow should store its log files
      #- ./logs:/usr/local/airflow/logs
      # Configuration File
      - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg
      - /var/run/docker.sock:/var/run/docker.sock
      # For custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    networks:
      air_rest:
        ipv4_address: 172.18.0.5
      air_db:
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 15s
      timeout: 15s
      retries: 3
    container_name: airflow
volumes:
  datavolume: 

networks:
  air_rest:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
  air_db:
